# Generated by Django 3.2.4 on 2021-06-30 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField(choices=[(1, 'Ну такое себе'), (2, 'Ничего так'), (3, 'Нормульно'), (4, 'Хорошо'), (5, 'Классно!')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='book.bookreview')),
            ],
        ),
    ]
