# Generated by Django 3.2.4 on 2021-06-24 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0006_auto_20210623_1302'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField(choices=[(1, 'Ну такое себе'), (2, 'Ничего так'), (3, 'Нормульно'), (4, 'Хорошо'), (5, 'Классно!')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='book.bookreview')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_mark', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('book', 'owner')},
            },
        ),
    ]
