# Generated by Django 3.2.4 on 2021-06-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='book_author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='preview',
            field=models.TextField(),
        ),
    ]
