# Generated by Django 3.2.4 on 2021-06-22 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('book', '0003_auto_20210622_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='category.category'),
        ),
    ]
