# Generated by Django 3.2.4 on 2021-06-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='BookImages',
        ),
    ]
